name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          npm install --no-save @testiny/cli@latest
          
      - name: Run tests and submit to Testiny
        env:
          TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
          TESTINY_PROJECT_ID: "3"
        run: python scripts/report_to_testiny.py
  complete-test-run:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Complete test run
        env:
          TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
        run: |
          npx @testiny/cli automation \
            --project 3 \
            --source pytest-tests \
            --field-values job_id=${{ github.job }},attempt=${{ github.run_attempt }} \
            --run-fields ci_repository,ci_run_id,job_id,attempt \
            --complete-runs