name: Run Python Tests & Report to Testiny

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pytest
        pip install -r requirements.txt

    - name: Run tests and save results
      run: |
        pytest --tb=short --json-report --json-report-file=results.json

    - name: Report test results to Testiny
      run: |
        python scripts/report_to_testiny.py
      env:
        TESTINY_TOKEN: ${{ secrets.TESTINY_TOKEN }}
